/* This file is generated, DO NOT EDIT!!! All changes will get
   overwritten.
   Edit ../mintlib/syscalls.list in the MiNTLib distribution instead.  */

#define SYS_write 0
#define SYS_fstat 1
#define SYS_times 2
#define SYS_pause 3
#define SYS_rename 4
#define SYS_truncate 5
#define SYS_waitpid 6
#define SYS_wait 7
#define SYS_wait3 8
#define SYS_wait4 9
#define SYS_readdir 10
#define SYS_fsync 11
#define SYS_lstat 12
#define SYS_dup2 13
#define SYS_getppid 14
#define SYS_close 15
#define SYS_setgid 16
#define SYS_statfs 17
#define SYS_sigaction 18
#define SYS_sigblock 19
#define SYS_signal 20
#define SYS_sigpause 21
#define SYS_sigpending 22
#define SYS_sigreturn 23
#define SYS_sigsetmask 24
#define SYS_fork 25
#define SYS_symlink 26
#define SYS_readlink 27
#define SYS_ioctl 28
#define SYS_stty 29
#define SYS_gtty 30
#define SYS_ftruncate 31
#define SYS_creat 32
#define SYS_fcntl 33
#define SYS_setsid 34
#define SYS_setuid 35
#define SYS_umask 36
#define SYS_kill 37
#define SYS_killpg 38
#define SYS_gettimeofday 39
#define SYS_settimeofday 40
#define SYS_getitimer 41
#define SYS_setitimer 42
#define SYS_getpriority 43
#define SYS_setpriority 44
#define SYS_nice 45
#define SYS_link 46
#define SYS_lseek 47
#define SYS_execve 48
#define SYS_getgid 49
#define SYS_rmdir 50
#define SYS_getegid 51
#define SYS_getuid 52
#define SYS_pipe 53
#define SYS_getpid 54
#define SYS_dup 55
#define SYS_setregid 56
#define SYS_alarm 57
#define SYS_geteuid 58
#define SYS_setreuid 59
#define SYS_chdir 60
#define SYS_access 61
#define SYS_getgroups 62
#define SYS_chown 63
#define SYS_select 64
#define SYS_getrusage 65
#define SYS_initgroups 66
#define SYS_setgroups 67
#define SYS_getrlimit 68
#define SYS_setrlimit 69
#define SYS_read 70
#define SYS_open 71
#define SYS_flock 72
#define SYS_utime 73
#define SYS_mkdir 74
#define SYS_stat 75
#define SYS_sync 76
#define SYS_chmod 77
#define SYS_unlink 78
#define SYS_chroot 79
#define SYS_fchmod 80
#define SYS_fchown 81
#define SYS_fpathconf 82
#define SYS_getdtablesize 83
#define SYS_gethostid 84
#define SYS_getpagesize 85
#define SYS_getpgrp 86
#define SYS_mkfifo 87
#define SYS_mknod 88
#define SYS_pathconf 89
#define SYS_poll 90
#define SYS_sbrk 91
#define SYS_setegid 92
#define SYS_seteuid 93
#define SYS_setpgid 94
#define SYS_setpgrp 95
#define SYS_sigprocmask 96
#define SYS_sigsuspend 97
#define SYS_sigvec 98
#define SYS_stime 99
#define SYS_sysinfo 100
#define SYS_time 101
#define SYS_uname 102
#define SYS_utimes 103
#define SYS_vfork 104
#define SYS_getdomainname 105
#define SYS_gethostname 106
#define SYS_setdomainname 107
#define SYS_sethostname 108
